# Define default parameters
QUERY: 'artificial intelligence'
MAX_ABSTRACTS: 50
NGRAM_MIN: 1
NGRAM_MAX: 1
TOP_N: 3
DIVERSITY_ALGO: 'mmr' # or 'maxsum'
DIVERSITY: 0.2 # For MMR
NR_CANDIDATES: 20 # For MaxSum
